development:
  adapter: postgresql
  encoding: unicode
  database: charlie_and_dogs
  pool: 5
  username: ornitorrinko
  password: orni123

test:
  adapter: postgresql
  encoding: unicode
  database: charlie_and_dogs_test
  pool: 5
  username: ornitorrinko
  password: orni123

production:
  adapter: postgresql
  encoding: unicode
  database: charlie_and_dogs_prod
  pool: 5
  username: ornitorrinko
  password: orni123
